<?php

namespace Eye3\CaminosBundle\Entity;
use Doctrine\ORM\EntityRepository;


use Eye3\CaminosBundle\Entity\Aditivo;

/**
 * AditivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AditivoRepository extends EntityRepository
{

		//formato fecha desde y hasta "yyyy-mm-dd"
		public function GraficarAditivo($desde = "2014-12-01" ,$hasta = "2015-02-28")
		{
			$query = $this->getEntityManager()
				->getConnection()
				->prepare(
					"select * from aditivo join usuario on usuario = usuario.id WHERE fecha BETWEEN :desde and :hasta order by fecha"

			);
				$query->bindValue('desde', $desde );
				$query->bindValue('hasta', $hasta." 23:59:59" );

			 $query->execute();
			 
			 return $query->fetchAll();
		}
		
		//formato año "yyyy"
		public function historial_excel( $ano = "2014" )
		{

			$query = $this->getEntityManager()
				->getConnection()
				->prepare(
					"select *, null as NombreTramo, null as NombreZona, null as value from aditivo join usuario on usuario = usuario.id WHERE fecha like :desde order by fecha;"

			);
				$query->bindValue('desde', $ano.'%' );

				$query->execute();
			 
			 return $query->fetchAll();
		}
		
		public function InicioDatos()
		{ 
			
			$query = $this->getEntityManager()
			->getConnection()
			->prepare(
				"SELECT min(fecha) FROM aditivo"
			);
			
			$query->execute();

			return $query->fetchcolumn(0);
		}

	public function FinalDatos()
		{ 
			
			$query = $this->getEntityManager()
			->getConnection()
			->prepare(
				"SELECT max(fecha) FROM aditivo"
			);
			
			$query->execute();

			return $query->fetchcolumn(0);
		}

}
		
