<?php

namespace Eye3\CaminosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AditivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AditivoRepository extends EntityRepository
{
}
