<?php

namespace Eye3\CaminosBundle\Entity;
use Doctrine\ORM\EntityRepository;


use Eye3\CaminosBundle\Entity\Gpsdata;

/**
 * GpsdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpsdataRepository extends EntityRepository
{

		
		public function GetAreas()
		{
				$query = $this->getEntityManager()
				->getConnection()
				->prepare(
					'SELECT id,NombreZona from zonaMapa'
				);

			$query->execute();
			return $query->fetchAll();
		}
		
		
		public function GetTramos($area=null)
		{
				$query = $this->getEntityManager()
				->getConnection()
				->prepare(
					'SELECT id,NombreTramo from tramoMapa'.(is_null($area)?'':" where zonaid = $area")
				);

			$query->execute();
			return $query->fetchAll();
		}
		
		public function GetTramo($tramo_id = 51)
		{
				$query = $this->getEntityManager()
				->getConnection()
				->prepare(
					'SELECT NumPoints(tramo) from graficarMapa where id = '.$tramo_id
				);

			$query->execute();
			$cantidad= $query->fetchColumn(0);
			
			if (!is_numeric($cantidad)) return NULL;
			
			for($punto=1;$punto<$cantidad+1;$punto++)
			{
				
				$query = $this->getEntityManager()
				->getConnection()
				->prepare(
					"SELECT X(PointN(tramo,$punto)) as X ,Y(PointN(tramo,$punto)) as Y from graficarMapa where id = $tramo_id"
				);
				$query->execute();
				$puntos[]= $query->fetch();
			}
			
			return $puntos;

		}

}
		
