<?php

namespace Eye3\CaminosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanriegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanriegoRepository extends EntityRepository
{
	public function LastDato()
		{ 
			
			$query = $this->getEntityManager()
			->getConnection()
			->prepare(
				"SELECT max(id)  FROM planRiego "
			);
			
			$query->execute();

			return $query->fetchcolumn(0);
		}
}
