<?php

namespace Eye3\CaminosBundle\Entity;
use Doctrine\ORM\EntityRepository;


use Eye3\CaminosBundle\Entity\Pmdata;

/**
 * PmdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PmdataRepository extends EntityRepository
{

		
		
		public function GetPuntos($fecha = "031214")
		{
			$query = $this->getEntityManager()
				->createQuery(
					'SELECT dato FROM Eye3CaminosBundle:Pmdata dato where dato.date = :fecha'
				)->setParameter('fecha', $fecha);;

			try {
				return $query->getResult();
			} catch (\Doctrine\ORM\NoResultException $e) {
				return null;
			}
			 
		}

}
		
